apiVersion: apps/v1
kind: Deployment
metadata:
  name: elasticsearch-publisher
  labels:
    app: elasticsearch-publisher
spec:
  replicas: 1
  selector:
    matchLabels:
      app: elasticsearch-publisher
  template:
    metadata:
      labels:
        app: elasticsearch-publisher
    spec:
      containers:
      - name: elasticsearch-publisher
        image: harlend100/orchestrator
        env:
          - name: RABBITMQ
            value: "databases-rabbitmq"
          - name: RABBITQUEUE
            value: "root.stages[name=load].source_queue"
          - name: RABBITPASS
            valueFrom:
              secretKeyRef:
                name: databases-rabbitmq
                key: rabbitmq-password
                optional: false
          - name: ESENDPOINT
            value: p1ic4302-es-elastic-user
          - name: ESPASSWORD
            valueFrom:
              secretKeyRef:
                name: p1ic4302-es-elastic-user
                key: elastic
                optional: false
          - name: MDB_USERNAME
            value: root
          - name: MDB_PASSWORD
            value: "1234"
          - name: MDB_HOST
            value: "host.docker.internal"
          - name: MDB_DATABASE
            value: estudiantesTEC
          - name: JOBINDEX
            value: jobs
          - name: GROUPINDEX
            value: groups
       
