apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-connector
  labels:
    app: mysql-connector
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql-connector
  template:
    metadata:
      labels:
        app: mysql-connector
    spec:
      containers:
      - name: mysql-connector
        image: harlend100/mysql-connector
        env:
          - name: RABBITMQ
            value: "databases-rabbitmq"
          - name: RABBITQUEUE
            value: "ready"
          - name: RABBITQUEUEDEST
            value: "%{transform->transformation->add_car}%"
          - name: RABBITPASS
            valueFrom:
              secretKeyRef:
                name: databases-rabbitmq
                key: rabbitmq-password
                optional: false
          - name: ESENDPOINT
            value: p1ic4302-es-default
          - name: ESPASSWORD
            valueFrom:
              secretKeyRef:
                name: p1ic4302-es-elastic-user
                key: elastic
                optional: false
          - name: MDB_USERNAME
            value: root
          - name: MDB_PASSWORD
            value: "1234"
          - name: MDB_HOST
            value: "host.docker.internal"
          - name: MDB_DATABASE
            value: estudiantesTEC
          - name: JOBINDEX
            value: jobs
          - name: GROUPINDEX
            value: groups
