apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
  labels:
    app: api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
      - name: api
        image: harlend100/api
        ports:
        - containerPort: 5000
        - containerPort: 8000
        env:
          - name: MONGO_STRING
            value: "mongodb+srv://hdanielqg:hola1234@proyecto2.y96zzh2.mongodb.net/?retryWrites=true&w=majority&appName=Proyecto2"
          - name: NEO4J_URI
            value: "neo4j+s://demo.neo4jlabs.com"
          - name: NEO4J_USER
            value: "movies"
          - name: NEO4J_PASSWORD
            value: "movies"
          - name: NEO4J_VERSION
            value: "4"
          - name: NEO4J_DATABASE
            value: "movies"
          - name: PORT
            value: "8080"

